/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent_of_code_2022;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class DayOneTest {
    @Test void someLibraryMethodReturnsTrue() {
        List<String> inputLines = Utils.readInputLinesFromFile("day_one.txt");
        DayOne dayOne = new DayOne(inputLines);
        assertThat(dayOne.solvePart1()).isEqualTo(Integer.MAX_VALUE);
    }
}
