/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent_of_code_2022;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class DayOneTest {

    @Test
    void partA() {
        List<String> inputLines = Utils.readInputLinesFromFile("testinput.txt");
        DayOne dayOne = new DayOne(inputLines);
        assertThat(dayOne.solvePart1()).isEqualTo(24000);
    }

    @Test
    void partB() {
        List<String> inputLines = Utils.readInputLinesFromFile("testinput.txt");
        DayOne dayOne = new DayOne(inputLines);
        assertThat(dayOne.solvePart2()).isEqualTo(45000);
    }
}
