/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent_of_code_2022;

import java.util.List;

public class DayOne {
    private List<String> inputLines;

    public DayOne(List<String> inputLines) {
        this.inputLines = inputLines;
    }

    public int solvePart1() {
        throw new UnsupportedOperationException("Not yet implemented!");
    }
}
