/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package advent_of_code_2022;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

public class DayOne {
    private List<String> inputLines;

    public DayOne(List<String> inputLines) {
        this.inputLines = inputLines;
    }

    public int solvePart1() {
        int max_calories = 0;
        int totalCalories = 0;
        for (String line : inputLines) {
            if (line.isEmpty()) {
                if (totalCalories > max_calories) {
                    max_calories = totalCalories;
                }
                totalCalories = 0;
            } else {
                totalCalories += Integer.parseInt(line);
            }
        }
        if (totalCalories > max_calories) {
            max_calories = totalCalories;
        }

        return max_calories;
    }

    public int solvePart2() {
        List<Integer> result = new ArrayList<>();
        int totalCalories = 0;
        for (String line : inputLines) {
            if (line.isEmpty()) {
                result.add(totalCalories);
                totalCalories = 0;
            } else {
                totalCalories += Integer.parseInt(line);
            }
        }
        result.add(totalCalories);

        return result.stream().sorted(Comparator.reverseOrder()).limit(3).mapToInt(Integer::intValue).sum();
    }
}
